### ISSUE TITLE
litd panic after poold RPC request while lnd is locked

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/lightning-terminal#155]
This is a bit of an edge case today but may become a common problem in the future when the Pool UI is used by more people.

Steps to reproduce:
- run `litd` in integrated mode
- unlock `lnd` with `lncli unlock`
- open the UI in a browser and login
- restart `litd` so that `lnd` is now locked
- trigger a `loopd` gRPC request from the UI (click on the Loop button)
- observe an error notification is displayed stating:
   ```
   loop is not yet ready for requests, lnd possibly still starting or syncing
   ```
- trigger a `poold` gRPC request from the UI
- observe an error notification is displayed stating:
   ```
   Response closed without headers
   ```
- switch to the terminal where `litd` is running and see that the process has ended by a panic error

Logs from startup to panic:
```
2020-11-30 23:58:05.101 [INF] LTND: Version: 0.11.1-beta commit=lightning-terminal-v0.3.0-alpha-98-g88f0ac0ad27002bf7f30bf74c8e8c691877f1839, build=production, logging=default
2020-11-30 23:58:05.101 [INF] LTND: Active chain: Bitcoin (network=testnet)
2020-11-30 23:58:05.101 [INF] LTND: Opening the main database, this might take a few minutes...
2020-11-30 23:58:05.101 [INF] LTND: Opening bbolt database, sync_freelist=false
2020-11-30 23:58:06.213 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
2020-11-30 23:58:06.214 [INF] LTND: Database now open (time_to_open=1.112434896s)!
2020-11-30 23:58:06.225 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
2020-11-30 23:58:06.225 [INF] LITD: Dialing lnd gRPC server at 127.0.0.1:10009
2020-11-30 23:58:06.225 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2020-11-30 23:58:06.226 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2020-11-30 23:58:06.351 [INF] LITD: Setting up Let's Encrypt for server <snipped>
2020-11-30 23:58:06.351 [INF] LITD: Setting up Let's Encrypt with cache dir /root/.lit/letsencrypt
----------------------------------------------------------
 Lightning Terminal (LiT) by Lightning Labs

 Operating mode      integrated
 Node status         locked
 Alias               <snipped>
 Version             0.11.1-beta
 Web interface       https://127.0.0.1:443
----------------------------------------------------------
2020-11-30 23:58:06.351 [INF] LITD: Listening for http_tls on: [::]:443
2020-11-30 23:58:06.351 [INF] LITD: Listening for Let's Encrypt challenges on :80
2020-11-30 23:58:09.990 [INF] LITD: Handling gRPC web request: /looprpc.SwapClient/GetLoopInTerms
2020-11-30 23:58:31.124 [INF] LITD: Handling gRPC web request: /looprpc.SwapClient/GetLoopInTerms
2020-11-30 23:59:49.114 [INF] LITD: Handling static file request: /static/js/7.834e0fb0.chunk.js
2020-11-30 23:59:49.146 [INF] LITD: Handling static file request: /static/js/7.834e0fb0.chunk.js.map
2020-12-01 00:00:02.388 [INF] LITD: Handling gRPC web request: /looprpc.SwapClient/GetLoopInTerms
2020-12-01 00:00:19.518 [INF] LITD: Handling static file request: /static/js/6.13009629.chunk.js
2020-12-01 00:00:19.559 [INF] LITD: Handling static file request: /static/js/6.13009629.chunk.js.map
2020-12-01 00:00:21.030 [INF] LITD: Handling static file request: /static/js/4.4c5af2e1.chunk.js.map
2020-12-01 00:00:21.050 [INF] LITD: Handling static file request: /static/js/8.05dcdb19.chunk.js.map
2020-12-01 00:00:21.060 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListAccounts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdb6cc0]

goroutine 105 [running]:
github.com/lightningnetwork/lnd/macaroons.(*Service).ValidateMacaroon(0x0, 0x1c35380, 0xc0003724b0, 0xc000281380, 0x1, 0x1, 0xc00003fba0, 0x1c, 0xc0003722d0, 0xc0000d7280)
	/root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.11.1-beta/macaroons/service.go:255 +0x220
github.com/lightninglabs/pool.(*Server).ValidateMacaroon(...)
	/root/go/pkg/mod/github.com/lightninglabs/pool@v0.3.3-alpha/server.go:359
github.com/lightninglabs/lightning-terminal.(*LightningTerminal).ValidateMacaroon(0xc0005621c0, 0x1c35380, 0xc0003724b0, 0xc000281380, 0x1, 0x1, 0xc00003fba0, 0x1c, 0x0, 0xc0003722d0)
	/root/dev/shushtar/terminal.go:409 +0x325
github.com/lightninglabs/lightning-terminal.(*rpcProxy).StreamServerInterceptor.func1(0x0, 0x0, 0x1c3ee20, 0xc00027c300, 0xc000116160, 0xc000380c10, 0x1c35380, 0xc0003722d0)
	/root/dev/shushtar/rpc_proxy.go:270 +0x1be
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00036fd40, 0x1c44b80, 0xc000324090, 0xc000290100, 0x0, 0xc000281aa0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1336 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00036fd40, 0x1c44b80, 0xc000324090, 0xc000290100, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1415 +0xb33
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000138120, 0xc00036fd40, 0x1c44b80, 0xc000324090, 0xc000290100)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```
> Note the `loopd` gPRC requests (`/looprpc.SwapClient/GetLoopInTerms`) returned an error but didn't cause a panic

**Comment by guggero** [comment]
Nice catch! I think we should probably not serve any RPC requests for Loop/Pool/Faraday until they are properly started. I'll try to return a generic error instead.

**Comment by jamaljsr** [comment]
Agreed, an error similar to the one returned by `GetLoopInTerms` would be fine.
