### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by emretezel** [lightninglabs/lightning-terminal#227]
Hi Everyone,

Getting the following build error when trying to compile LiT from source, version 0.4.1-alpha

```
ubuntu@ip-172-31-47-210:~/opt/code/lightning-terminal$ make install
 Installing app dependencies with yarn
cd app; yarn
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.56s.
 Building production app.
cd app; yarn build
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
/home/ubuntu/opt/code/lightning-terminal/app/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: Failed to load config "prettier/@typescript-eslint" to extend from.
Referenced from: /home/ubuntu/opt/code/lightning-terminal/app/.eslintrc
    at configMissingError (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
    at ConfigArrayFactory._loadExtends (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:378:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:397:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:18)
    at FileEnumerator._iterateFilesWithFile (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/file-enumerator.js:365:43)
    at FileEnumerator._iterateFiles (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/file-enumerator.js:346:25)
    at FileEnumerator.iterateFiles (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/cli-engine.js:770:48) {
  messageTemplate: 'extend-config-missing',
  messageData: {
    configName: 'prettier/@typescript-eslint',
    importerName: '/home/ubuntu/opt/code/lightning-terminal/app/.eslintrc'
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:134: app-build] Error 1
```

**Comment by guggero** [comment]
I'm not sure what the problem is here. But by googling I found this: https://stackoverflow.com/questions/65675771/eslint-couldnt-find-the-config-prettier-typescript-eslint-after-relocating

@jamaljsr do we need to update anything in the ESLint config?

**Comment by emretezel** [comment]
Thank you, are you able to tell the required version of node.js, npm and eslint packages?

**Comment by emretezel** [comment]
I have completely removed node, npm and yarn, then installed yarn, came with node

```
ubuntu@ip-172-31-47-210:~/opt/code/lightning-terminal$ yarn --version
1.22.5
ubuntu@ip-172-31-47-210:~/opt/code/lightning-terminal$ node --version
v10.19.0
```

Completely deleted LiT folder, fresh close from github, checked out latest tag, and then

```
ubuntu@ip-172-31-47-210:~/opt/code/lightning-terminal$ make install
 Installing app dependencies with yarn
cd app; yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.2.1: The platform "linux" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning " > mobx-react-lite@3.0.1" has incorrect peer dependency "react@^16.8.0".
warning " > mobx-utils@5.6.1" has incorrect peer dependency "mobx@^4.13.1 || ^5.13.1".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react@^16.0.0".
warning "rc-tooltip > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react-dom@^16.0.0".
warning " > @typescript-eslint/eslint-plugin@4.7.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > @typescript-eslint/parser@4.7.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > eslint-plugin-react@7.21.5" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning "@storybook/react > @babel/plugin-transform-react-constant-elements@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react@7.12.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-object-rest-spread@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/addon-docs > @babel/plugin-transform-react-jsx@7.12.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > react-virtualized@9.21.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.21.2" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > reactour@1.18.0" has incorrect peer dependency "react@^16.3.0".
warning " > reactour@1.18.0" has incorrect peer dependency "react-dom@^16.3.0".
warning " > reactour@1.18.0" has unmet peer dependency "react-is@^16.8".
warning "reactour > react-focus-lock@2.2.1" has incorrect peer dependency "react@^16.8.0".
warning "reactour > react-focus-lock > react-clientside-effect@1.2.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning "reactour > react-focus-lock > use-callback-ref@1.2.4" has incorrect peer dependency "react@^16.8.0".
warning "reactour > react-focus-lock > use-sidecar@1.0.3" has incorrect peer dependency "react@^16.8.0".
warning " > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "@storybook/addon-actions > @storybook/api@5.3.19" has unmet peer dependency "regenerator-runtime@*".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning " > @storybook/addon-docs@5.3.19" has unmet peer dependency "babel-loader@^8.0.0".
warning " > @storybook/addon-docs@5.3.19" has incorrect peer dependency "react@^16.8.0".
warning " > @storybook/addon-docs@5.3.19" has unmet peer dependency "react-is@^16.8.0".
warning "@storybook/addon-docs > @egoist/vue-to-react@1.1.0" has incorrect peer dependency "react@^16.8.6".
warning "@storybook/addon-docs > @egoist/vue-to-react@1.1.0" has unmet peer dependency "vue@^2.6.10".
warning "@storybook/addon-docs > vue-docgen-loader@1.5.0" has unmet peer dependency "webpack@>=4".
warning "@storybook/addon-docs > vue-docgen-api > @vue/compiler-sfc@3.0.2" has unmet peer dependency "vue@3.0.2".
warning "@storybook/react > @babel/preset-flow@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/preset-create-react-app@3.1.2" has unmet peer dependency "@babel/core@*".
warning "@storybook/preset-create-react-app > react-docgen-typescript-plugin > react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > @storybook/react@5.3.19" has unmet peer dependency "@babel/core@^7.0.1".
warning " > @storybook/react@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @storybook/core@5.3.19" has unmet peer dependency "@babel/core@*".
warning "@storybook/react > @storybook/core@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning " > @testing-library/user-event@12.2.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > eslint-config-prettier@6.15.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-plugin-prettier@3.1.4" has unmet peer dependency "eslint@>=5.0.0".
[4/4] Building fresh packages...
Done in 89.58s.
 Building production app.
cd app; yarn build
yarn run v1.22.5
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
/home/ubuntu/opt/code/lightning-terminal/app/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: Failed to load plugin 'prettier' declared in '.eslintrc': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /home/ubuntu/opt/code/lightning-terminal/app/node_modules/react-scripts/config/__placeholder__.js
Referenced from: /home/ubuntu/opt/code/lightning-terminal/app/.eslintrc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.resolve (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1011:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:831:29)
    at ConfigArrayFactory._loadExtends (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:778:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:378:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:397:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:18)
    at FileEnumerator._iterateFilesWithFile (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/file-enumerator.js:365:43)
    at FileEnumerator._iterateFiles (/home/ubuntu/opt/code/lightning-terminal/app/node_modules/eslint/lib/cli-engine/file-enumerator.js:346:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:134: app-build] Error 1
```

Very frustrating, why all the peer dependencies missing warnings? 

I would have thought yarn would take care of loading all dependencies. 

More detailed instructions on how to install from source would be very appreciated.

**Comment by guggero** [comment]
Yes, `yarn` should take care of the dependencies. Can you try again with Node.JS version 12 or later?

**Comment by emretezel** [comment]
Let me try that, I thought the problem was using the latest version of Node such as 14.

**Comment by emretezel** [comment]
Still failing with v12.18.1

**Comment by emretezel** [comment]
Failing with node.js 16.1.0 as well same error message as before, somehow not all modules are being downloaded

**Comment by emretezel** [comment]
Solved the issue, the entire problem was due to me setting an env variable earlier called NODE_ENV=production. Removing the env variable fixed the issue. Thanks for your time.

**Comment by guggero** [comment]
Okay, good to know. Happy you're able to build from source now.
