### ISSUE TITLE
Lit crashed while using terminal web

### ISSUE THREAD

**Issue by kiwiidb** [lightninglabs/lightning-terminal#323]
Lit crashed with the following logs:
```
2022-02-11 13:02:15.858 [INF] SESS: Checking for schema update: latest_version=0, db_version=0
2022-02-11 13:02:15.859 [INF] LITD: Dialing lnd gRPC server at localhost:10009
2022-02-11 13:02:15.867 [INF] SESS: Mailbox RPC server listening on mailbox:bb426aca72e5da67ae43a737ffe829058490a68fa742f55cc7517d2ff1974f0aea78db3c7e3e8cfb7b2fd7622df3fb6a1e7ffc2162fca8c5ce90485e6a742a1c@mailbox.terminal.lightning.today:443
2022-02-11 13:02:15.867 [INF] LITD: Listening for http_tls on: 127.0.0.1:8443
----------------------------------------------------------
 Lightning Terminal (LiT) by Lightning Labs               
                                                          
 Operating mode      remote                                   
 Node status         online                                   
 Alias               flitz-v2-lnd1                                   
 Version             0.14.1-beta commit=basedon-v0.14.1-beta-fresh-btcpay                                   
 Web interface       127.0.0.1:8443 (open https://127.0.0.1:8443 in your browser)         
----------------------------------------------------------
2022-02-11 13:02:16.098 [INF] LNDC: Creating lnd connection to localhost:10009
2022-02-11 13:02:16.099 [INF] LNDC: Connected to lnd
2022-02-11 13:02:16.108 [INF] LNDC: Waiting for lnd to unlock
2022-02-11 13:02:16.110 [INF] LNDC: Wallet state of lnd is now: Lnd RPC server is ready for requests
2022-02-11 13:02:16.128 [INF] LNDC: lnd version: v0.14.1-beta, build tags 'signrpc,walletrpc,chainrpc,invoicesrpc,routerrpc'
2022-02-11 13:02:16.129 [INF] LNDC: Using network regtest
2022-02-11 13:02:16.129 [INF] LNDC: Waiting for lnd to be fully synced to its chain backend, this might take a while
2022-02-11 13:02:26.924 [INF] LOOPD: Monitor request received
panic: assignment to entry in nil map

goroutine 121 [running]:
github.com/lightninglabs/loop/loopd.(*swapClientServer).Monitor(0xc0002f0c88, 0x10, {0x28a8530, 0xc0004f2160})
	github.com/lightninglabs/loop@v0.15.1-beta/loopd/swapclient_server.go:283 +0x2ad
github.com/lightninglabs/loop/looprpc._SwapClient_Monitor_Handler({0x16e4820, 0xc0002f0c80}, {0x289e348, 0xc0003e03c0})
	github.com/lightninglabs/loop@v0.15.1-beta/looprpc/client_grpc.pb.go:405 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0001eec40, {0x28b00f0, 0xc0004c9680}, 0xc0000cca20, 0xc000506cc0, 0x3448a60, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1541 +0xe44
google.golang.org/grpc.(*Server).handleStream(0xc0001eec40, {0x28b00f0, 0xc0004c9680}, 0xc0000cca20, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1621 +0x9e5
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:938 +0x294
```

Used this dockerfile: https://github.com/vafanassieff/crypto-docker/blob/master/lightning-terminal/Dockerfile
Running inside Kubernetes, on regtest.
Port-forward to pod, copy pairing phrase, import into terminal.lightning.engineering. Click around a bit: everything seemed to work, some things were slow to load though. Then the session seemed to be disconnected and I saw the pod had crashed.

**Comment by guggero** [comment]
It looks like your `lnd` node isn't fully synced to the network yet and isn't fully started up. Wait for the node to sync (you might need to mine a new block on regtest if the last one is more than 2 hours old)

**Comment by kiwiidb** [comment]
Thank you for the quick reply. This was indeed the issue (now there is a different error that causes litd to crash).
However I'd say that a request should not cause a `panic` because the back-end is still syncing, it should check this first and return an error.

**Comment by guggero** [comment]
Yes, I agree that we should fix this.
